### ISSUE TITLE
Prusa B x-offset

### ISSUE THREAD

**Issue by Andi-Heidelberg** [heidelberg-makerspace/do-something#57] opened 2016-09-07 19:40 UTC
Some offset in printed part occured while printing today, We. 07.sep .

**Comment by emka** [comment] 2016-09-07 19:47
MIght be related to #52 but the cause is not clear yet.

**Comment by LukasFreeze** [comment] 2016-09-07 22:27
Not sure if related, but the x-axis belt is way too loose and needs to be tightened in the course of this repair.

**Comment by emka** [comment] 2016-09-21 18:46
The first print worked fine today, second is still running.

**Comment by LukasFreeze** [comment] 2016-09-26 14:00
If prints work out again this Wednesday we could close this for now, but the loose belt remains an imperfection that should be tackled the next time parts on the machine need to be altered anyway.

This time, reducing the "X-Y-jerk distance" (distance allowed to travel at full speed rather than gradual acceleration) from 15 to 5 mm was all I did.

**Comment by beanobeano** [comment] 2016-10-04 11:57
Did a hi-tech hack to tighten the belt with a piece of bent coat hanger.
Running a test print now.

**Comment by LukasFreeze** [comment] 2016-10-05 13:08
two successful and long runs later, I'd say this is closed but feel free to improve @beanobeano's hack (e.g. adjustable with screw)

**Closed by LukasFreeze** 2016-10-05 13:08 UTC
Labels: 3D printing, bug

**Comment by Andi-Heidelberg** [comment] 2016-10-06 19:06
This was simple and clever, and it works! Great! :-)

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: beanobeano <notifications@github.com> </div><div>Datum:04.10.2016  13:57  (GMT+01:00) </div><div>An: heidelberg-makerspace/do-something <do-something@noreply.github.com> </div><div>Cc: Andi-Heidelberg <dekonstruktor@gmx.de>, Author <author@noreply.github.com> </div><div>Betreff: Re: [heidelberg-makerspace/do-something] Prusa B x-offset (#57) </div><div>
</div>Did a hi-tech hack to tighten the belt with a piece of bent coat hanger.
Running a test print now.
